# To See H2 Console in Browser:
# http://localhost:8080/h2-console
# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: "jdbc:h2:~/.chat_db"
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
